### ISSUE TITLE
Incorrect rendering when emulating document modes 8/9 in IE11

### ISSUE THREAD

**Issue by simevidas** [jonathantneal/flexibility#13]
I’ve created a quick demo: https://jsbin.com/giwavu/edit?css,output. (Note: replace `/edit...` in the URL with `/quiet` when testing in IE.)

Result in IE11:
![capture0](https://cloud.githubusercontent.com/assets/716405/11989692/b4d5a960-aa02-11e5-806e-1cfd2ff7286f.PNG)

After switching to Document mode: 9 (Emulation panel in F12 tools):
![capture](https://cloud.githubusercontent.com/assets/716405/11989710/e627ea5a-aa02-11e5-9b78-b47768bd2db0.PNG)

Document mode: 8
![capture2](https://cloud.githubusercontent.com/assets/716405/11989712/ebecea6c-aa02-11e5-8162-8b92d232d34b.PNG)

**Comment by jonathantneal** [comment]
There are 2 issues here.

First, in Example 4, you are using [`flex`] to assign the [`flex-basis`] of each item. I have yet added support for `flex-basis` and it does not already exist in [css-layout]. Alternatively, if you use `flex: 1` or `flex-grow: 1` then you’ll get the desired effect. If you would like support for `flex-basis`, I encourage you to [create an issue](https://github.com/facebook/css-layout/issues/new) in [css-layout]. Any improvement to css-layout becomes an improvement to Flexibility.

Second, in Example 2, you are using `margin: auto` on the second item to give it space. I’ll look into how `auto` margins function so that I can add support into Flexibility. This may be another issue to file with [css-layout].

[`flex`]: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
[css-layout]: https://github.com/facebook/css-layout

**Comment by jonathantneal** [comment]
Margin auto is now supported, and this issue hasn’t been responded to in a while, so I’m closing it. Of course, feel free to open a new one if you are experiencing new or similar problems :)
